[package]
name = "prefetch-benchmark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amiquip = "0.4.2"
rand = "0.8.5"

[dependencies.openssl]
version = "0.10.29"
features = [
    "vendored"
]
