version: "3.8"
services:
  pb-consumer:
    build: .
    container_name: pb-consumer
    depends_on:
      - rabbitmq
    environment:
      ROLE: CONSUMER
      PREFETCH_COUNT: 10
      WORKLOAD_TIME: 0
      CONNECTION_STRING: amqp://guest:guest@rabbitmq:5672
      NAME: C1
    networks:
          - pb-net
  pb-producer:
    build: .
    container_name: pb-producer
    depends_on:
      - rabbitmq
      - pb-consumer
    environment:
      ROLE: PRODUCER
      MESSAGE_COUNT: 100000
      MESSAGE_LEN: 1000
      TIME_BETWEEN_MSG: 0
      CONNECTION_STRING: amqp://guest:guest@rabbitmq:5672
    networks:
          - pb-net
  rabbitmq:
    image: rabbitmq:3.10-management-alpine
    container_name: 'pb-rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    # volumes:
    #     - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    #     - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - pb-net

networks:
  pb-net:
    driver: bridge
