version: "3.8"
services:
  pb-consumer:
    deploy:
      replicas: 50
      
        
    build: .
    depends_on:
      - rabbitmq
      - tc
    environment:
      ROLE: CONSUMER
      #PREFETCH_COUNT: 50
      CONSUMER_COUNT: 50
      MESSAGE_COUNT: 300
      WORKLOAD_TIME: 100
      CONNECTION_STRING: amqp://guest:guest@rabbitmq:5672
      NAME: C1
    labels:
      com.docker-tc.enabled: 1
      com.docker-tc.delay: "50ms"
    networks:
          - pb-net
  pb-producer:
    build: .
    container_name: pb-producer
    depends_on:
      - rabbitmq
      - pb-consumer
    environment:
      ROLE: PRODUCER
      MESSAGE_COUNT: 300
      MESSAGE_LEN: 5000
      TIME_BETWEEN_MSG: 0
      CONNECTION_STRING: amqp://guest:guest@rabbitmq:5672
    networks:
          - pb-net
  rabbitmq:
    image: rabbitmq:3.10-management-alpine
    container_name: 'pb-rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    # volumes:
    #     - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    #     - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - pb-net
  tc:
    image: "lukaszlach/docker-tc"
    container_name: docker-tc
    cap_add:
      - NET_ADMIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/docker-tc:/var/docker-tc
    deploy:
      mode: global
    environment:
      HTTP_BIND: 127.0.0.1
      HTTP_PORT: 4080
    network_mode: host
networks:
  pb-net:
    driver: bridge
